dist: xenial
language: cpp
compiler: clang
install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update skip errors
  - sudo apt-get install libboost1.71-all-dev
addons:
  apt:
    packages:
    - doxygen
    - graphviz
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -f -T bulk_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uashatalov:$BINTRAY_API_KEY "https://api.bintray.com/content/ashatalov/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/bulk_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
